version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: Portainer
    restart: unless-stopped
    ports:
      - 18000:9000   # web
      - 18001:8000   # agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
