version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: "mysql-container"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    networks: 
      lbd_aula:
        ipv4_address: 172.10.0.4

networks: 
  lbd_aula:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 172.10.0.0/24  